// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAODqDXaaAkmNgvBom8guBhj3bYqb07Tyc',
    appId: '1:652813445754:web:d778d140a16339d274e9c3',
    messagingSenderId: '652813445754',
    projectId: 'bakso-cakwi',
    authDomain: 'bakso-cakwi.firebaseapp.com',
    storageBucket: 'bakso-cakwi.firebasestorage.app',
    measurementId: 'G-YSWYMHQX74',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1fp53LeBpTVyNmPup6z6FMKrXOHjfHik',
    appId: '1:652813445754:android:8db2fa9458b181b874e9c3',
    messagingSenderId: '652813445754',
    projectId: 'bakso-cakwi',
    storageBucket: 'bakso-cakwi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwSST6mCKBGv4m-7bzj_-u2w_M_pBjzSg',
    appId: '1:652813445754:ios:ea692a679bf268b274e9c3',
    messagingSenderId: '652813445754',
    projectId: 'bakso-cakwi',
    storageBucket: 'bakso-cakwi.firebasestorage.app',
    iosBundleId: 'com.example.geraiBakso',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwSST6mCKBGv4m-7bzj_-u2w_M_pBjzSg',
    appId: '1:652813445754:ios:ea692a679bf268b274e9c3',
    messagingSenderId: '652813445754',
    projectId: 'bakso-cakwi',
    storageBucket: 'bakso-cakwi.firebasestorage.app',
    iosBundleId: 'com.example.geraiBakso',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAODqDXaaAkmNgvBom8guBhj3bYqb07Tyc',
    appId: '1:652813445754:web:382346730d53983474e9c3',
    messagingSenderId: '652813445754',
    projectId: 'bakso-cakwi',
    authDomain: 'bakso-cakwi.firebaseapp.com',
    storageBucket: 'bakso-cakwi.firebasestorage.app',
    measurementId: 'G-N3X3CYQKWK',
  );
}
